### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by rakaiv5** [jayneelparekh/sp2si-code#1]
You guys did a nice job, thank you

**Comment by ghost** [comment]
@rakaiv5 were you able to run the evaluation?
@jayneelparekh would helpful to have a google colab for the evaluation code

**Comment by jayneelparekh** [comment]
@ak9250 I'll definitely add a notebook as soon as I find time. Meanwhile if you are facing any specific issue do let me know. I'll try to resolve it here. (Also please note that I have updated the documentation and code)

**Comment by rakaiv5** [comment]
Hi, I was just learning part of the code and I didn't run it yet~
I will talk to you when I meet some issue, thank you!
