### ISSUE TITLE
Training code unavailable

### ISSUE THREAD

**Issue by shoutong** [jayneelparekh/sp2si-code#3]
Hi, thanks for sharing the evaluation code. Would you please release the training code so we can reproduce the result from scratch.

**Comment by jayneelparekh** [comment]
Hello @shoutong,

The training script is not clean and hence I refrained from uploading it here. Due to other commitments I probably won't work on cleaning it in the near future. Nevertheless, if you need it, please send me an email at jayneelparekh@gmail.com, I'll be happy to share it.
